"""
Add Exam Mode Column

Purpose:
    Adds a 'mode' column to the Exam table to distinguish between different exam types
    (e.g., "hybrid", "online", "physical").
"""
"""add_exam_mode

Revision ID: 2b0652d7a369
Revises: e3fb95734dac
Create Date: 2025-12-15 15:45:45.941817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '2b0652d7a369'
down_revision: Union[str, None] = 'e3fb95734dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'mode')
    # ### end Alembic commands ###
