"""
Add Manual Review Fields

Purpose:
    Updates the `evaluation` table to support the "Human-in-the-Loop" workflow.
    - `review_requested`: Flag raised by AI (low confidence) or student.
    - `student_comment`: Argument from student contesting the grade.
    - `teacher_comment`: Final feedback from the teacher after manual review.
"""
"""Add manual review fields

Revision ID: 72cf4f597cf1
Revises: 2b0652d7a369
Create Date: 2025-12-16 16:46:51.458524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '72cf4f597cf1'
down_revision: Union[str, None] = '2b0652d7a369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation', sa.Column('review_requested', sa.Boolean(), nullable=True))
    op.add_column('evaluation', sa.Column('student_comment', sa.Text(), nullable=True))
    op.add_column('evaluation', sa.Column('teacher_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation', 'teacher_comment')
    op.drop_column('evaluation', 'student_comment')
    op.drop_column('evaluation', 'review_requested')
    # ### end Alembic commands ###
