"""add_rag_tables

Revision ID: 8aad58807788
Revises: 72cf4f597cf1
Create Date: 2025-12-27 18:21:36.188224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '8aad58807788'
down_revision: Union[str, None] = '72cf4f597cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_material_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['coursematerial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_material_chunk_id'), 'course_material_chunk', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_material_chunk_id'), table_name='course_material_chunk')
    op.drop_table('course_material_chunk')
    # ### end Alembic commands ###
