"""
Enable pgvector Extension

Purpose:
    Explicitly enables the `vector` extension in PostgreSQL.
    This is required for storing high-dimensional embeddings (e.g., from OpenAI/SentenceTransformer)
    used in the RAG system.
"""
"""enable_pgvector_extension

Revision ID: 8f45752e6582
Revises: 8aad58807788
Create Date: 2025-12-27 22:54:08.294518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '8f45752e6582'
down_revision: Union[str, None] = '8aad58807788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
