"""
Add Student-Course Enrollment Table

Purpose:
    Creates a Many-to-Many association table `student_courses`.
    This maps Students to the Courses they are enrolled in.
"""
"""add_student_courses_table

Revision ID: 9bd55d5bb290
Revises: 8f45752e6582
Create Date: 2026-01-02 17:34:25.068752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9bd55d5bb290'
down_revision: Union[str, None] = '8f45752e6582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_courses',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_courses')
    # ### end Alembic commands ###
